/** Central route table (avoids stringly-typed navigation). */
export const ROUTES = {
  signup: "/signup",
  verifyEmail: "/verify-email",
  verifyEmailSuccess: "/verify-email/success",
  verifyEmailExpired: "/verify-email/expired",
  login: "/login",
  accountLocked: "/account-locked",
  forgotPassword: "/forgot-password",
  forgotPasswordSent: "/forgot-password/sent",
  resetPassword: "/reset-password",
  resetPasswordSuccess: "/reset-password/success",
  resetPasswordExpired: "/reset-password/expired",
  dashboard: "/dashboard",
  vacancies: "/vacancies",
  vacancyNew: "/vacancies/new",
  vacancyDetail: "/vacancies/:id",
  bids: "/bids",
  offers: "/offers",
  invoices: "/invoices",
  messages: "/messages",
  settings: "/settings",
  settingsProfile: "/settings/profile",
  settingsTeam: "/settings/team",
  settingsBenefits: "/settings/benefits",
  settingsBilling: "/settings/billing",
  settingsNotifications: "/settings/notifications",
  settingsSecurity: "/settings/security",
  settingsActivityLog: "/settings/activity-log",
  settingsDataPrivacy: "/settings/data-privacy",

  // Recruiter / Agency portal
  recruiterGetStarted: "/recruiter/get-started",
  recruiterSignup: "/recruiter/signup",
  agencySignup: "/recruiter/agency-signup",
  recruiterOnboarding: "/recruiter/onboarding",
  agencyOnboarding: "/recruiter/agency-onboarding",
  recruiterUnderReview: "/recruiter/under-review",
  recruiterActionRequired: "/recruiter/action-required",
  recruiterUnsuccessful: "/recruiter/unsuccessful",
  recruiterDashboard: "/recruiter/dashboard",
  recruiterTeam: "/recruiter/team",
  recruiterMarketplace: "/recruiter/marketplace",
  recruiterCandidates: "/recruiter/candidates",
  recruiterCandidateDetail: "/recruiter/candidates/:id",
  recruiterSubmissions: "/recruiter/submissions",
  recruiterSubmitToVacancy: "/recruiter/submit-to-vacancy",
  recruiterEarnings: "/recruiter/earnings",
} as const;
